name: integrate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  matrix:
    name: "GCC"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        GCC: [9, 10, 11]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19.0"
      - uses: actions/cache@v3
        env:
          cache-name: bazel
        with:
          path: ~/.cache/bazelisk
          key: ${{ env.cache-name }}-${{ runner.os }}
          restore-keys: |
            ${{ env.cache-name }}-${{ runner.os }}
      - run: go install github.com/bazelbuild/bazelisk@latest
      - name: run build
        env:
          CC: gcc-${{ matrix.GCC }}
          CXX: g++-${{ matrix.GCC }}
        run: |
          bazelisk test //...
